name: neural-research
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - jupyter>=1.0.0
  - streamlit>=1.28.0
  - aiohttp>=3.8.0
  - aiofiles>=0.8.0
  - pytest>=7.0.0
  - coverage>=6.0.0
  - pathlib2
  - pip
  - pip:
    - mcp-agent
    - mcp-server-git
    - anthropic
    - asyncio-mqtt
    - PyPDF2>=2.0.0
    - docling

variables:
  NEURAL_ENV: "activated"
  CONDA_ENV_NAME: "neural-research"
  PYTHONPATH: "${CONDA_PREFIX}/lib/python3.10/site-packages"
