model:
  embedding_dim: 64
  gcn_layers: 2
  diffusion_steps: 1000
  diffusion_beta_start: 0.0001
  diffusion_beta_end: 0.02
  denoiser_hidden_dim: 128
  dropout: 0.1
training:
  batch_size: 1024
  learning_rate: 0.001
  epochs: 100
  weight_decay: 0.0001
  negative_samples: 4
  loss_weights:
    bpr: 1.0
    denoising: 0.1
    regularization: 0.01
data:
  user_item_path: data/user_item.csv
  user_user_path: data/user_user.csv
  test_ratio: 0.2
  val_ratio: 0.1
experiment:
  seed: 42
  device: cuda
  checkpoint_dir: checkpoints/
  log_dir: logs/
  eval_every: 10
