"""Server notification names implemented in P1."""

THREAD_UPDATED = "thread.updated"
SERVER_WARNING = "server.warning"
TERMINAL_OUTPUT = "terminal.output"
TERMINAL_EXIT = "terminal.exit"
SKILLS_CHANGED = "skills.changed"
PLUGINS_CHANGED = "plugins.changed"
MCP_CHANGED = "mcp.changed"
SETTINGS_CHANGED = "settings.changed"
